name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:                          #for testing purposes. it gives a button to trigger the workflow without push or pull the changes to repo
jobs:
    hello:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: hello world
          run: echo "hello world"
          shell: bash

    goodbye:
      runs-on: ubuntu-latest
      steps:
        - name: goodbye world
          run: echo "goodbye world"
          shell: bash
    check-bats-version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                node-version: '14'
            - run: npm install -g bats
            - run: bats -v



